### ISSUE TITLE
Various issues with tag

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#1066]
Folks are reporting a number of issues after the changes between 6a11ff8 and 2b6f9a7.  It's been temporarily reverted on enwiki (with #908/#1044 kept), but we've got:

- [x] Duplicate tags ([TW:TW](https://en.wikipedia.org/w/index.php?oldid=969477664#Bug_report:_Duplicate_tags)) (Fixed by #1063, though we may want to [tweak that](https://github.com/azatoth/twinkle/pull/1063#issuecomment-663888752))
- [ ] Blank checkboxes (partially fixed by #1059) ([TW:TW](https://en.wikipedia.org/w/index.php?oldid=969477664#Error_on_tag))
- [x] Broken re-initialization of sort order changes (reported at #1061 by @Xi-Plus) (Unrelated)

I cannot replicate any of these behaviors, and the first two are at least mutually exclusive.  Some sort of race condition?

**Comment by Amorymeltzer** [comment]
I can now replicate the duplicate tags in Safari only, and it's an issue in `getInputData`

**Comment by Amorymeltzer** [comment]
With no new information and 2/3 of the concerns resolved, I've restored the changes.  I have a suspicion that the blank checkboxes being unsolved by #1059 was a caching issue, but regardless, I can't look into it without more information.  Hopefully everything either works or there can be more information.

**Comment by Amorymeltzer** [comment]
No complaints on the blank checkboxes since restoration, so I'm assuming it was just a false report after some caching issues with the fix from #1059.  Closing as successful!
