### ISSUE TITLE
XfD: Only show valid options

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#753]
Currently, all XfD options are shown on pages. However,
* [?] Afd should only be shown for articles
* [?] Tfd should only be shown for templates and modules
* [x] Ffd should only be shown for files (#865)
* [x] Cfd & Cfds should only be shown for categories and templates (stubs) (#897, #926)
* [?] Rfd should only be shown for redirects (including category redirects)
* [x] RM should not be shown for categories (#865)
* [ ] <s>None</s> Only MfD should be shown for mediawiki namespace

**Comment by Amorymeltzer** [comment]
So basically enforce the defaults, give or take?  I suppose I'm not opposed to it; I can see some value in leaving AfD/RfD/MfD vague-ish for edge cases, but I have no idea how often that happens.  I presume @azatoth's initial intent was ease plus entrusting the user, this goes back a decade.

>None should be shown for mediawiki namespace

MfD

**Comment by DannyS712** [comment]
Okay, then leave MfD.

**Comment by siddharthvp** [comment]
At least the AfD option should be set disabled if on a redirect, solving #379. And probably RM too in category namespace -- but that may be confusing and we can't put any tooltip next to a disabled option, so I think it would be better to allow the option but when selected, display some red text telling the user to use CfD/CfDS instead. We could use the red text option for former case too.

**Comment by Amorymeltzer** [comment]
I'm fine with just disabled, at least on the 100% cases (which you've noted); can add a note to the dropdown tooltip that some items may be disabled.

**Comment by Amorymeltzer** [comment]
#865 will do files and rm, as clearly appropriate low-hanging fruit.  I think it's worth discussing some of the others a bit, but I'm a little wary of disabling things like AfD/RfD on redirect status.  Well (or not so well) meaning users sometimes redirect/unredirect and but for a revert we occasionally end up with pages that are redirects that should head to AfD, or vice-versa.  Not opposed to it, but I think it's worth considering whether we need to be heavy-handed about it.  It's possible some of the ideas in #379 would be a better solution (should also be discussed).
