### ISSUE TITLE
warn: Adjustments to ensure hidden comment matching works properly (tracking)

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#923]
`twinklewarn` finds prior templates given, and checks to see if any were given recently or if the same one in question was given within 24 hours.  It relies on the hidden html comment to do this, but some templates have non-standard comments, so aren't matched. 
 Ignoring those that redirect to something included in Twinkle (e.g. to the `{{uw-generic}}` series or `{{uw-vandalism4}}`), I think that leaves the following as potential problem-makers:

#### Errors (edit on-wiki)
- [X] uw-error4: Had `uw-vandalism4`
- [X] uw-own4im: Had `uw-disruptive3` since it's inception in 2011

#### Weird spacing (edit on-wiki)
- [x] uw-aiv: Formatted as `Uw-AIV`, leftover from 2007 move
- [X] uw-vgscope: Space after `Template:`
- [X] uw-copyright-new: No spaces between comment tags and comment (also dealt with in #922)

#### Capitalized `U` in `Uw-` (PR)
- [X] Change regex matching rather than bulk editing (although that'd probably be fine)
    * #922
<details>
<summary>List</summary>

- uw-paid1
- uw-paid2
- uw-paid3
- uw-paid4
- uw-harass2
- uw-tempabuse2
- uw-deadlink
- uw-elinbody
- uw-english
- uw-notvote
- uw-plagiarism
- uw-warn
- uw-attack
- uw-hijacking
- uw-login
- uw-multipleIPs
- uw-salt
- uw-socksuspect
- uw-userspace draft finish
</details>

#### Non-standard/not really a `uw-` template
- [x] uw-draftfirst: Redirects to [[Template:Draft suggestion]]
- [x] uw-sofixit: Redirects [[Template:Sofixit]]

**Comment by Amorymeltzer** [comment]
On the topic of `uw-aiv`, it looks like @ToBeFree was running into similar issues in Huggle exactly two years ago.  AFAICT the relevant HG config is https://en.wikipedia.org/w/index.php?title=User:ToBeFree/Huggle-Config-Sandbox.yaml&oldid=835841956 and, based on that format, a search turns up no config pages that'd be messed up by changing it to `uw-aiv`, but wanted to double-check first.

**Comment by Amorymeltzer** [comment]
For the last item, regarding `uw-draftfirst` and `uw-sofixit`, I think I'm fine removing them both; it does appear that both are used, albeit only maybe a half dozen+ times a month (draftfirst) and a couple of times a month (sofixit).

The alternative is to add Twinkle's respective `uw-` redirect in another hidden comment; this is already done a few times elsewhere fwiw (I think just `uw-selfrevert`, `uw-tpv4`, and `uw-talkinarticle`).

**Comment by ToBeFree** [comment]
> On the topic of `uw-aiv`, it looks like @ToBeFree was running into similar issues in Huggle exactly two years ago. AFAICT the relevant HG config is https://en.wikipedia.org/w/index.php?title=User:ToBeFree/Huggle-Config-Sandbox.yaml&oldid=835841956 and, based on that format, a search turns up no config pages that'd be messed up by changing it to `uw-aiv`, but wanted to double-check first.

Hmm, I'm not sure – you're probably referring to https://en.wikipedia.org/w/index.php?title=Template:Uw-aiv&diff=835846656&oldid=687459207&diffmode=source , but uw-aiv is currently not included in Huggle's automatic detection, and doesn't need to be automatically detected as a L1 warning by Twinkle either. If a user receives a uw-aiv warning instead of a block for their AIV report, they have made a good-faith attempt at reporting something that could have been appropriate for WP:ANI. Interpreting this as a reason for an automatic warning escalation would be a bit far-fetched anyway.

If I understand it correctly, I'd say that the uw-aiv issue mentioned in https://github.com/azatoth/twinkle/issues/923#issue-599234714 is not actually an issue (wontfix/invalid).

**Comment by ToBeFree** [comment]
For a list of templates currently detected by Huggle, and the level associated with them, see "warning-template-tags" at https://en.wikipedia.org/wiki/Wikipedia:Huggle/Config.yaml

**Comment by Amorymeltzer** [comment]
I went and added the comment on-wiki to the two remaining templates, so this is all set! Turns outdraftfirst got renamed to uw-draftfirst.
